name: pipeline

on: [push]
env: 
  APPLICATION_NAME: app_0.01
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code in repo
      uses: actions/checkout@v4
    - name: Setup Python Environment
      uses: actions/setup-python@v4
    - name: Install Requirements
      run: |
        pip install --quiet --requirement requirements.txt
    - name: Lint Code
      run: |
        flake8 --ignore=E501,E231 *.py
        pylint --disable=C0301 --disable=C0326 *.py
    - name: Run unit test
      run: |
        python -m unittest --verbose --failfast
  
  build-image:
    needs: [lint]
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout code
      uses: actions/checkout@v4
    - name: setup gcloud
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '274.0.1'
        service_account_email: ${{ secrets.GCP_SERVICE_ACCT_EMAIL }}
        service_account_key: ${{ secrets.GCP_SERVICE_ACCT_KEY }}
    - run: |
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        gcloud config set run/region ${{ secrets.GCP_REGION }}
        gcloud auth configure-docker
        gcloud info
    - name: build and tag image
      run: docker build -t "gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.APPLICATION_NAME }}:latest" .
    - name: Push docker image to registry
      run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.APPLICATION_NAME }}:latest    


